kind: pipeline
name: default
type: docker

steps:
  - name: test
    pull: if-not-exists
    image: registry.atyx.ru/price_books
    commands:
      - python3 project/manage.py test project

  - name: publish
    image: plugins/docker
    settings:
      registry: registry.atyx.ru
      repo: registry.atyx.ru/price_books
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password

image_pull_secrets:
  - dockerconfigjson
