# Generated by Django 3.0.5 on 2020-05-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200505_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='loader_type',
            field=models.CharField(choices=[('em', 'ЭКСМО'), ('l2', 'Азбука-КоЛибри-Махаон-Иностранка')], default='em', max_length=2, verbose_name='Загрузчик'),
            preserve_default=False,
        ),
    ]
