# Generated by Django 3.0.5 on 2020-05-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author_search',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Автор (поиск)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_search',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Название (поиск)'),
        ),
    ]
