# Generated by Django 3.0.5 on 2020-05-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200504_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='binding',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Переплет'),
        ),
        migrations.AddField(
            model_name='product',
            name='binding_search',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Переплет (поиск)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='binding',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Переплет'),
        ),
    ]
