# Generated by Django 3.0.5 on 2020-05-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200504_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус'),
        ),
    ]
