# Generated by Django 3.0.5 on 2020-05-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Найденное количество товаров'),
        ),
    ]
