# Generated by Django 3.0.5 on 2020-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_supplier_loader_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='publisher',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Издатель'),
        ),
    ]
