# Generated by Django 3.0.5 on 2020-05-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200507_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
    ]
