# Generated by Django 3.0.6 on 2020-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20200507_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author_search',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор (поиск)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_search',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (поиск)'),
        ),
    ]
