# Generated by Django 3.0.6 on 2020-05-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200510_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='article',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='loader_type',
            field=models.CharField(choices=[('em', 'ЭКСМО'), ('l2', 'Азбука-КоЛибри-Махаон-Иностранка'), ('ak', 'Аквилегия'), ('pt', 'Питер'), ('kk', 'Книжный клуб'), ('am', 'ТД Амадеос'), ('zc', 'Загря center'), ('um', 'Умка'), ('is', 'ИнтерСервис')], max_length=2, verbose_name='Загрузчик'),
        ),
    ]
