# Generated by Django 3.0.6 on 2020-05-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20200512_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Celery task id'),
        ),
        migrations.AddField(
            model_name='order',
            name='task_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery task status'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Celery task id'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='task_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery task status'),
        ),
    ]
